@startuml

Class Patient

Class Claims


Class ServiceLine
{
name : Many2one(product.template)
sale_price : Float
vendor_price : Float
patient_price : Float
price_plan : Many2one(PricePlan)
}

@enduml
