@startuml

Visit o..* Patient : patient_id
Visit o..* MedicalCenter : medical_center_id
Visit *..o ServiceLine : service_line_id

ServiceLine *..o PricePlan : price_plan
ServiceLine o..* Product : product_id


PricePlan o..* MedicalCenter : medical_center_id

Patient o..* PricePlan : price_plan

MedicalCenter --> Partner
Patient --> Partner

Class Partner

Class MedicalCenter{
    price_plan :O2M
    visit : O2M
}

Class ServiceLine
{
    name : M2O
    sale_price : Float
    vendor_price : Float
    patient_price : Float
    price_plan : M2O
}


Class Visit{

    name : Char
    price_plan : Char
    patient_status : Boolean
    contribution_charge : Float
    patient_charge : Float
    date_of_visit :  Datetime
    visit_type :  Char
    plan_status : Char
    visit_state : Selection
    patient_id : M2O
    medical_center_id : M2O
    service_line_id : M2O
}

Class PricePlan{
    name : Char
    state : Selection
    start_date : Date
    end_date :  Date
    medical_center_id : M2O
    service_line : O2M
}

Class Patient{
    NID : Char
    date_of_birth : Date
    gender : Selection
    marital_status : Selection
    blood_group : Char
    weight : Float
    height : Float
    status : Boolean
    visit : O2M

}

Class PatientLine{
    price_plan : M2O
    patient : M2O
    paid_cost : Float
    remain_cost : Float
    status : Boolean
    compute_remain_cost()
}


Class Visit{

    name : Char
    price_plan : Char
    patient_status : Boolean
    contribution_charge : Float
    patient_charge : Float
    date_of_visit :  Datetime
    visit_type :  Char
    plan_status : Char
    visit_state : Selection
    patient_id : Many2one(Patient)
    medical_center_id : Many2one(MedicalCenter)
    service_line_id : Many2one(ServiceLine)
}

@enduml
